version: '3'
services:
  python3:
    restart: always
    build: ./infra/python
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./backend/:/root
      - ./infra/python/cpp/:/root/.config/atcoder-cli-nodejs/cpp